parameter_defaults:
  CinderEnableIscsiBackend: false
  CinderEnableRbdBackend: false
  CinderEnableNfsBackend: false
  NovaEnableRbdBackend: false
  CinderDefaultVolumeType: infinidat-iscsi1
  CinderRpcResponseTimeout: 180
  NovaLibvirtVolumeUseMultipath: true
  MultipathdEnable: true
  MultipathdCustomConfigFile: /var/lib/mistral/multipath.conf
  ControllerExtraConfig:
    cinder::config::cinder_config:
      infinidat-iscsi1/volume_driver:
        value: cinder.volume.drivers.infinidat.InfiniboxVolumeDriver
      infinidat-iscsi1/volume_backend_name:
        value: infinidat-iscsi1
      infinidat-iscsi1/san_ip:
        value: infinibox.domain.com
      infinidat-iscsi1/san_login:
        value: censored
      infinidat-iscsi1/san_password:
        value: censored
      infinidat-iscsi1/san_thin_provision:
        value: true
      infinidat-iscsi1/driver_use_ssl:
        value: true
      infinidat-iscsi1/suppress_requests_ssl_warnings:
        value: true
      infinidat-iscsi1/infinidat_pool_name:
        value: rhsop_cinder_pool1
      infinidat-iscsi1/infinidat_storage_protocol:
        value: iscsi
      infinidat-iscsi1/infinidat_iscsi_netspaces:
        value: default_iscsi_space
      infinidat-iscsi1/san_thin_provision:
        value: true
      infinidat-iscsi1/use_multipath_for_image_xfer:
        value: true
      infinidat-iscsi1/image_volume_cache_enabled:
        value: false
      infinidat-iscsi2/volume_driver:
        value: cinder.volume.drivers.infinidat.InfiniboxVolumeDriver
      infinidat-iscsi2/volume_backend_name:
        value: infinidat-iscsi2
      infinidat-iscsi2/san_ip:
        value: infinibox.domain.com
      infinidat-iscsi2/san_login:
        value: censored
      infinidat-iscsi2/san_password:
        value: censored
      infinidat-iscsi2/san_thin_provision:
        value: true
      infinidat-iscsi2/driver_use_ssl:
        value: true
      infinidat-iscsi2/suppress_requests_ssl_warnings:
        value: true
      infinidat-iscsi2/infinidat_pool_name:
        value: rhsop_cinder_pool2
      infinidat-iscsi2/infinidat_storage_protocol:
        value: iscsi
      infinidat-iscsi2/infinidat_iscsi_netspaces:
        value: default_iscsi_space
      infinidat-iscsi2/san_thin_provision:
        value: true
      infinidat-iscsi2/use_multipath_for_image_xfer:
        value: true
      infinidat-iscsi2/image_volume_cache_enabled:
        value: false
    cinder_user_enabled_backends:
    - infinidat-iscsi1
    - infinidat-iscsi2
